version: '3.4'

services:
  raven_db:
    image: ravendb/ravendb
    environment:
      - RAVEN_Setup_Mode=None 
      - RAVEN_License_Eula_Accepted=true 
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    ports:
      - "8080:8080"
      - "38888:38888"

  elk:
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes